zuul:
   routes:
    ng-test:
      url: http://red-gateui1i01.test.healthe:8502/ng-test/
      sensitive-headers:
    customer-manager:
      url: http://red-gateui1i01.test.healthe:8502/
    customer-manager-service:
      url: http://red-gateui1i01.test.healthe:8504/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-int01.test.healthe:14331;databaseName=customer;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO