zuul:
   routes:
    ng-test:
      url: http://red-gateui1u01.test.healthe:8502/ng-test/
      sensitive-headers:
    customer-manager:
      url: http://red-gateui1u01.test.healthe:8502/
    customer-manager-service:
      url: http://red-gateui1u01.test.healthe:8504/
    dm-service:
      url: http://red-abmdm1u01.test.healthe:8500/dm-service/
    dm-ui:
      url: http://red-abmdm1u01.test.healthe:8502/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-uat01.test.healthe:14331;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: DM_App_User
    password: HgP73*Vm&HNihs73hsNY    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO