zuul:
  routes:
    dm-service:
          url: http://localhost:8080/dm-service/
    dm-ui:
      url: http://localhost:4200/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379   
  datasource:
    url: jdbc:h2:mem:HES_Config;
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    initialize: true 
    schema: classpath:/schema-h2.sql
    data: classpath:/data-h2.sql
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: DEBUG
    org.springframework: INFO    