zuul:
  host:
    connect-timeout-millis: 60000 # starting the connection 
    socket-timeout-millis: 120000  # monitor the continuous incoming data flow
  routes:
    customer-manager:
      url: https://pqa-customer-manager-static.hestest.com/customer-manager-ui/
    customer-manager-service:
      url: https://pqa-customer-manager-svc.hestest.com/customer-manager-service/
    claim-manager:
      url: https://pqa-claim-manager-static.hestest.com/claim-manager-ui/
    claim-manager-service:
      url: https://pqa-claim-manager-svc.hestest.com/claim-manager-service/
    dm-service:
      url: https://pqa-dm-route.hestest.com/dm-service/
    dm-ui:
      url: https://pqa-dm-route.hestest.com/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://SQL-pqa01.test.healthe:14332;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8   
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO