zuul:
  host:
    connect-timeout-millis: 60000 # starting the connection 
    socket-timeout-millis: 120000  # monitor the continuous incoming data flow
  routes:
    customer-manager:
      url: https://customer-manager-static.healthesystems.com/customer-manager-ui/
    customer-manager-service:
      url: https://customer-manager-svc.healthesystems.com/customer-manager-service/
    claim-manager:
      url: https://claim-manager-static.healthesystems.com/claim-manager-ui/
    claim-manager-service:
      url: https://claim-manager-svc.healthesystems.com/claim-manager-service/
    dm-service:
      url: https://dm-route.healthesystems.com/dm-service/
    dm-ui:
      url: https://dm-route.healthesystems.com/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://SQL-oltp1.tampa.healthe:1433;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: IntGatewayUser
    password: 8#6W%Vcb-s7kkP&t   
logging:
  level:
    com.healthesystems: INFO
    org.springframework.security: INFO
