zuul:
  host:
    connect-timeout-millis: 60000 # starting the connection 
    socket-timeout-millis: 120000  # monitor the continuous incoming data flow
  routes:
    ng-test:
      url: http://red-gateui1u01.test.healthe:8502/ng-test/
      sensitive-headers:
    customer-manager:
      url: https://uat-customer-manager-static.hestest.com/
    customer-manager-service:
      url: https://uat-customer-manager-svc.hestest.com/
    claim-manager:
      url: https://uat-claim-manager-static.hestest.com/
    claim-manager-service:
      url: https://uat-claim-manager-svc.hestest.com/
    dm-service:
      url: https://uat-dm-route.hestest.com/dm-service/
    dm-ui:
      url: https://uat-dm-route.hestest.com/dm-ui/
    
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-uat01.test.healthe:14331;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO