zuul:
   routes:
    ng-test:
      url: http://red-gateui1i01.test.healthe:8502/ng-test/
      sensitive-headers:
    customer-manager:
      url: http://int-uiapps1hr1.test.healthe:8503/customer-manager-service/
    customer-manager-service:
      url: http://int-uiapps1hr1.test.healthe:8505/customer-manager-ui/
    dm-service:
      url: https://int-dm-route.hestest.com/dm-service/
    dm-ui:
      url: https://int-dm-route.hestest.com/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-int01.test.healthe:14331;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO