zuul:
   routes:
    ng-test:
      url: http://sot-devops1043.test.healthe:8502/ng-test/
      sensitive-headers:
    customer-manager:
      url: http://sot-devops1043.test.healthe:8502/
    customer-manager-service:
      url: http://sot-devops1043.test.healthe:8504/
    dm-service:
      url: http://sot-devops1043.test.healthe:8500/dm-service/
    dm-ui:
      url: http://sot-devops1043.test.healthe:8502/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sot-devops1043.test.healthe:1433;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: developer
    password: letmein999 
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO