zuul:
   routes:
    dm-service:
      url: http://pqa-abmdm1hr1.test.healthe:8500/dm-service/
    dm-ui:
      url: http://pqa-abmdm1hr1.test.healthe:8502/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-uat01.test.healthe:14331;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO