zuul:
  routes:
    ng-test:
      url: http://localhost:8082/ng-test/
      sensitive-headers:
    customer-manager-svc:
      path: /customer-manager-service/**
      url: http://localhost:9000/
      sensitive-headers:
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379   
  datasource:
    url: jdbc:sqlserver://sql-dev01.test.healthe:14331;databaseName=customer;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: DEBUG    