zuul:
  host:
    connect-timeout-millis: 60000 # starting the connection 
    socket-timeout-millis: 120000  # monitor the continuous incoming data flow
  routes:
    ng-test:
      url: http://red-gateui1i01.test.healthe:8502/ng-test/
      sensitive-headers:
    customer-manager-service:
      url: http://int-uiapps1hr1.test.healthe:8503/customer-manager-service/
    customer-manager:
      url: http://int-uiapps1hr1.test.healthe:8505/
    claim-manager-service:
      url: http://int-uiapps1hr1.test.healthe:8506/claim-manager-service/
    claim-manager:
      url: http://int-uiapps1hr1.test.healthe:8508/
    dm-service:
      url: https://int-dm-route.hestest.com/dm-service/
    dm-ui:
      url: https://int-dm-route.hestest.com/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-int01.test.healthe:14331;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: IntGatewayUser
    password: Um?n97N7%yG!6&Yk    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO