zuul:
   routes:
    ng-test:
      url: http://127.0.0.1:8502/ng-test/
      sensitive-headers:
    customer-manager:
      url: http://127.0.0.1:8502/
    customer-manager-service:
      url: http://127.0.0.1:8504/
    dm-service:
      url: http://127.0.0.1:8500/dm-service/
    dm-ui:
      url: http://127.0.0.1:8502/dm-ui/
spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://sql-int01.test.healthe:14331;databaseName=HES_Config;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    username: customer
    password: bogey8    
logging:
  level:
    com.healthesystems: DEBUG
    org.springframework.security: INFO